### ISSUE TITLE
Status button differs from status page

### ISSUE THREAD

**Issue by Don42** [raumzeitlabor/rzl-homepage#119]
Status button in the header shows "offen". Status page shows red.

**Comment by else** [comment]
Reason for this is that the status API backend is not being updated anymore.

**Comment by echox** [comment]
aaand can we fix that or remove the "status" and link to the status page?

**Comment by else** [comment]
Sure, go ahead :+1: 

Fixing the status would actually be pretty cool.

**Comment by else** [comment]
It's not a bug, it's a feature ;)

**Comment by else** [comment]
Ich hab das jetzt mal behelfsweise geflickt und es geht jetzt, aber da müsste mal was neues her.
