### ISSUE TITLE
Self Quantization?

### ISSUE THREAD

**Issue by Cheatha** [raumzeitlabor/rzl-homepage#128]
Ich glaube, hier ist Quantified Self gemeint.

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|d4017becf0af60a27c0936c7659952e0a81455cc|`none`| #127 |[![#127](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/raumzeitlabor/rzl-homepage/pull/127)|

**Comment by silsha** [comment]
Ich glaube „Quantified Self“ ist verbreiteter.
