### ISSUE TITLE
Layout broken on /kontakt/anfahrt in Firefox

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-homepage#13]
This defect was introduced with fe7b6f825b2abcb71c250f908728ad8f4794d623.

Seems to be related to the negative margins set on the next buttons.

**Comment by blabber** [comment]
I propose to change the captions of the "next" buttons to reflect the case when they should be clicked ("gate is open" and "gate is closed"). It breaks the consistency of button captions, but makes fragile sorcery like aligning list items of nested lists using negative margins.

For me it looks like a robust and usable tradeoff.
