### ISSUE TITLE
Latest Blogpost is broken

### ISSUE THREAD

**Issue by abrock** [raumzeitlabor/rzl-homepage#131]
The latest post is broken in at least 3 ways:

1. Instead of the author's name "Bernd Lauert" is displayed.
2. In the title "MRMCD" was somehow replaced by "Mrmcd" and "2015:" went missing completely
3. [The single page](https://raumzeitlabor.de/blog/mrmcd-call-for-participation/) starts with &lt;p&gt; and ends with &lt;/p&gt;

**Comment by else** [comment]
fixed in 4cdb169cdd83350c94a973b7a8888b9ac10bb851
