### ISSUE TITLE
RSS: Use absolute urls

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-homepage#133]
https://validator.w3.org/feed/docs/warning/ContainsRelRef.html

**Comment by else** [comment]
I understand the problem but I don't know how to implement this properly. Ideas?

**Comment by blabber** [comment]
https://github.com/jessecrouch/jekyll-rss-absolute-urls ?

**Comment by else** [comment]
Cool! Exactly what I tried to get working by myself, but failed ^^

**Comment by tabascoeye** [comment]
:+1: use the (open)source, brah!
