### ISSUE TITLE
https://raumzeitlabor.de/events/index.html ist b0rken

### ISSUE THREAD

**Issue by blabber** [raumzeitlabor/rzl-homepage#135]
At least since yesterday the Events view is broken. Calling https://raumzeitlabor.de/events/index.html yields 

    Leider ist unser Kalender im Moment nicht erreichbar. Bitte versuch es später noch einmal.

**Comment by silsha** [comment]
Diese URL (von der die Events aktuell geladen werden) zeigt einen Heroku-Fehler:
https://raumzeitlabor.de/events/ical?accept=jcal&expand=true&start=1430431200&end=1433109599

Falls sich die URL bei @fruux geändert haben sollte, hier ist eine die geht:
https://p.fruux.com/c/a3298259302/81bae0fb-601c-47ee-ba92-460866466d90.ics?accept=jcal&expand=true&start=1430431200&end=1433109599

**Comment by else** [comment]
Das hier sollte momentan aktiv sein: https://github.com/raumzeitlabor/rzl-homepage-docker/blob/master/nginx.conf#L67

Bin unterwegs und kann mir das gerade nicht näher anschauen. Sind die URLs dieselben?

**Comment by else** [comment]
Scheint, als würde nginx die Upstream IP cachen.

    2015/05/16 21:15:06 [error] 27#0: *161063 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.17.0.2, server: raumzeitlabor.de, request: "GET /events/ical?accept=jcal&expand=true&start=1430431200&end=1433109599 HTTP/1.1", upstream: "https://[2a01:578:3::36f6:7e88]:443/c/a3298259302/81bae0fb-601c-47ee-ba92-460866466d90.ics?accept=jcal&expand=true&start=1430431200&end=1433109599", host: "raumzeitlabor.de"

Restart hat geholfen, aber ich schaue mal nach, ob man das konfigurieren kann.

**Comment by silsha** [comment]
Scheint wieder kaputt zu sein.
