### ISSUE TITLE
Bilder kaputt

### ISSUE THREAD

**Issue by felicitus** [raumzeitlabor/rzl-homepage#138]
Auf https://raumzeitlabor.de/bilder/ sind viele der Bilder kaputt.

**Comment by else** [comment]
Das ist schon länger so, und ich bin mir absolut nicht sicher, was da passiert ist. Die Bilder, die kaputt sind, sind alle schon etwas älter, und waren eigentlich weiter hinten.

Irgendwann hat jemand diese Bilder aktualisiert oder sowas, jedenfalls waren sie plötzlich oben und es gab Tumblr Events auf unserem Stream.

**Comment by abrock** [comment]
Das Problem tritt auch bei neuen Bildern auf, die nicht aktualisiert / sonstwie angefasst wurden, z.B. das [Bild mit den Laser-Testschüssen](http://log.raumzeitlabor.org/post/121923521726/laser-testschusse-auf-papier-mit-zunehme) sieht bei mir so aus:

![](https://raw.githubusercontent.com/abrock/Katzenfutter/master/rzl-homepage/defect-log.png)

**Comment by else** [comment]
https://superuser.com/questions/885657/why-do-images-from-some-tumblr-pages-not-load-but-using-wget-on-them-works
