### ISSUE TITLE
Review-Ninja kaputt

### ISSUE THREAD

**Issue by abrock** [raumzeitlabor/rzl-homepage#144]
Mein [Pull-Request für den Garnwahl-Blogbeitrag](https://github.com/raumzeitlabor/rzl-homepage/pull/143) hat 2 Sterne, das wird im Ninja-Kommentar auch angezeigt aber untendran steht immer noch, ein Test wäre "pending".

![](https://raw.githubusercontent.com/abrock/Katzenfutter/master/rzl-homepage/ninja-stars-do-not-appear.png)

**Comment by else** [comment]
Kein Bug der Homepage, bitte bei https://github.com/reviewninja/review.ninja reporten.
