### ISSUE TITLE
Seite sollte SHA-2-Zertifikat nutzen

### ISSUE THREAD

**Issue by lutoma** [raumzeitlabor/rzl-homepage#200]
Ist zwar eher was für die NOC-Liste, aber weil die eher weniger responsive ist mal hier…

Die Seite benutzt aktuell ein SHA-1-Zertifikat. Das sorgt dafür dass aktuelle Chromes einen Fehler anzeigen. https://shaaaaaaaaaaaaa.com/check/raumzeitlabor.de

Ganz generell sind die TLS-Settings suboptimal: https://www.ssllabs.com/ssltest/analyze.html?d=raumzeitlabor.de&s=5.9.77.39&latest

**Comment by tabascoeye** [comment]
Da könnte man sich mal mit dem @zakx unterhalten:
https://www.ssllabs.com/ssltest/analyze.html?d=tickets.events.ccc.de

**Comment by zakx** [comment]
```server {
[...]

	ssl on;
	ssl_certificate /etc/nginx/ssl/foo.crt;
	ssl_certificate_key /etc/nginx/ssl/foo.key;
	ssl_trusted_certificate /etc/nginx/ssl/ca.crt;
	ssl_dhparam /etc/nginx/ssl/dh4096.pem;

	ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

	resolver <nameserver-IP> <nameserver-IP-2> valid=300s;
	resolver_timeout 3s;
	ssl_protocols TLSv1.2;
	ssl_session_cache shared:SSL:10m;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_prefer_server_ciphers on;

	add_header Strict-Transport-Security max-age=63072000;
	add_header X-Frame-Options SAMEORIGIN;
	add_header X-Content-Type-Options nosniff;
}```

**Comment by tabascoeye** [comment]
:+1: ersguterjunge

**Comment by else** [comment]
Jo, danke, aber ein neues Zertifikat brauchen wir trotzdem.

**Comment by lutoma** [comment]
Naja, Zertifikate nur für die Hauptseite gibt's ja schon für unter 5€. Wenn wir's richtig machen wollen, sollten wir halt gleich ein neues Wildcard-Cert holen, das sind dann halt ~75€, das dürfte denke ich auch nicht unser finanzieller Ruin sein. Oder vielleicht ist der StartSSL-Account von @nazco noch aktiv?

**Comment by tabascoeye** [comment]
gibts bei letsencrypt wildcard certs?

**Comment by else** [comment]
Nein.

**Comment by nazco** [comment]
@lutoma Sorry, mein Account bei denen ist inzwischen abgelaufen und ich hatte mit denen auch schon Ärger wegen der RZL Domain. Die finden es nicht so geil wenn man für eine andere juristische Person Certs ausstellt.

**Comment by lutoma** [comment]
Mit dem neuen Cert ist das alles gefixt.
