### ISSUE TITLE
Thread ersteller account anzeigen lassen.

### ISSUE THREAD

**Issue by Plankins** [raumzeitlabor/rzl-homepage#202]
Wäre cool wenn man den account von einem thread starter anzeigen lassen könnte.

**Comment by abrock** [comment]
Welchen Account willst du wo anzeigen lassen? Auf der Website gibt es soweit ich das sehe weder Accounts noch Threads,

**Comment by Plankins** [comment]
Habs falsch ausgedrückt...
Im Blog, z.B. Ingo, hat das Agenda Diplom Event erstellt, dann könnte man auf ingos account.

**Comment by tabascoeye** [comment]
Du meinst die Avatare mit dem [[Benutzer]] im Wiki verlinken oder wie?

**Comment by Plankins** [comment]
Ja. Genau

**Comment by tabascoeye** [comment]
send pull request ;o)

**Comment by Plankins** [comment]
?  :D 
Ähhhh... Nochmal für dumme bitte xD

**Comment by abrock** [comment]
@Plankins : Wenn ich das richtig interpretiere hat @tabascoeye dich aufgefordert, das gewünschte Feature selbst zu implementieren und einen Pull-Request einzureichen.

**Comment by Plankins** [comment]
Komme mir jetzt irgendwie dumm vor.

**Comment by tabascoeye** [comment]
meintest du das ungefähr so: http://pr-203.rzl-homepage.raumzeitlabor.org/blog/ ?
(Man könnte noch den CSS style für diese <a> tag anpassen, damit die namen nicht blau und beim hovern unterstrichen sind...)
