### ISSUE TITLE
Terminbeschreibungen falsch

### ISSUE THREAD

**Issue by Cheatha** [raumzeitlabor/rzl-homepage#214]
Ich habe einen Termin am 13.12. (FFRN Workshop) eingetragen, der fälschlicherweise die Beschreibung des Stickseminars bekommen hat. Sowohl über die Kalender.pp als auch über fruux.com ist ersichtlich, dass ich eigentlich keine Beschreibung angegeben habe.
![screenshot 2015-11-23 11 02 49](https://cloud.githubusercontent.com/assets/125570/11333975/173a905a-91d2-11e5-8f24-aa41d596e43c.png)
![screenshot 2015-11-23 11 01 52](https://cloud.githubusercontent.com/assets/125570/11333978/176777b4-91d2-11e5-8db8-1e022c735787.png)
![screenshot 2015-11-23 11 01 38](https://cloud.githubusercontent.com/assets/125570/11333977/175eecca-91d2-11e5-93ee-34d58cb4029e.png)

**Comment by tabascoeye** [comment]
Ich vermute das Problem ist irgendwo hier:
https://github.com/raumzeitlabor/rzl-homepage/blob/master/app/scripts/events.js#L65

eigentlich sollte die "description" ein necessary field sein, aber der check klappt wohl nicht so wie er soll (Zeile 74).
Evtl muss in zeile 69 zu dem `if()` noch ein `else`, das `ev[props[0]]` mit einem leeren String befüllt?

**Comment by else** [comment]
Ja, so siehts aus.

    [
        "vevent",
        [
            [
                "dtstart",
                {},
                "date-time",
                "2015-12-13T12:00:00Z"
            ],
            [
                "uid",
                {},
                "text",
                "167923e3-cf10-48e2-85dd-ec8d04e911d8"
            ],
            [
                "created",
                {},
                "date-time",
                "2015-11-23T10:00:11Z"
            ],
            [
                "dtstamp",
                {},
                "date-time",
                "2015-11-23T10:00:45Z"
            ],
            [
                "dtend",
                {},
                "date-time",
                "2015-12-13T17:00:00Z"
            ],
            [
                "location",
                {},
                "text",
                "Workshopraum"
            ],
            [
                "summary",
                {},
                "text",
                "FFRN Workshop"
            ],
            [
                "x-fruux-url",
                {},
                "unknown",
                "/calendars/a3298259302/81bae0fb-601c-47ee-ba92-460866466d90/167923e3-cf10-48e2-85dd-ec8d04e911d8.ics"
            ]
        ],
        []
    ],

**Comment by tabascoeye** [comment]
stale
