### ISSUE TITLE
Eventkalender sollte im aktuellen Monat per Default nur Termine in der Zukunft anzeigen

### ISSUE THREAD

**Issue by lutoma** [raumzeitlabor/rzl-homepage#235]
Wenn man aktuell gegen Ende des Monats auf den Terminkalender geht, stehen ganz oben immer noch die Termine vom Anfang des Monats, die schon vorbei sind. Die sollten vermutlich per JavaScript ausgeblendet werden und stattdessen einen Link haben »alte Termine im Monat anzeigen« oder so.

**Comment by tabascoeye** [comment]
@lutoma hat nur 5 Jahre gedauert ;)
