### ISSUE TITLE
Schilder auf Gelände aufhängen

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-homepage#238]
Um das RaumZeitLabor leichter zu finden könnten wir Schilder aufhängen.

Direkt am Tor ist eine Stange wo bereits Delta Werbetechnik hängt.

**Comment by lutoma** [comment]
Das ist vermutlich im falschen Repository gelandet und sollte ins [tuwat](https://github.com/raumzeitlabor/tuwat/issues).
