### ISSUE TITLE
Verbesserungslink beim Blättern kaputt

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-homepage#24]
Wenn man im Blog auf Seite 2 blättert führt der Link ins Github-Repo („Verbesserungsvorschlag?“) auf einen 404 Fehler.

**Comment by else** [comment]
Ja, ich befürchte allerdings, da kann man nix machen, außer man bekommt den Namen des Templates raus.

**Comment by tabascoeye** [comment]
Ich schlage vor, wir verlinken als "Verbesserungsvorschlag" auf https://github.com/raumzeitlabor/rzl-homepage/issues und closen das hier
