### ISSUE TITLE
English landing page

### ISSUE THREAD

**Issue by norpol** [raumzeitlabor/rzl-homepage#259]
There is no English landing page, and also no other English page describing RaumZeitLabor right?
https://wiki.raumzeitlabor.de/wiki/Das_RaumZeitLabor

**Comment by Bfritz0815** [comment]
@norpol There are some pages in the wiki that are in english but these were created years ago so the structure that once conneted it is no longer existing.
e.g.:
https://wiki.raumzeitlabor.de/wiki/Anfahrt/en
as english version for:
https://wiki.raumzeitlabor.de/wiki/Anfahrt

The Anfahrt-Page is up to date but on other articles some infos on english variants may have been insufficiently maintained. 
Wiki maintainance in any language has always been a kind of "someone should do it" kind of task here. (Which seems to be a typical Wiki-phenomenon. Sigh... )

Suggestion: If you have specific kinds of info that you would like to see in english, post a list here and i can look into creating english variants of the relevant pages. 

Currently requested:
- english version of: https://wiki.raumzeitlabor.de/wiki/Das_RaumZeitLabor

**Comment by lutoma** [comment]
I'll start translating some pages. An english version of our homepage has been on my todo for a while, but so far nothing much has happened due to software constraints™. But I guess now is as good as any time to get started on that again.
