### ISSUE TITLE
Mehrtägige Events

### ISSUE THREAD

**Issue by silsha** [raumzeitlabor/rzl-homepage#26]
Mehrtägige Events werden aktuell so dargestellt: 

![screen shot 2015-01-28 at 04 50 51](https://cloud.githubusercontent.com/assets/31850/5932182/4a5d775a-a6a9-11e4-9d29-2cd81f4b0037.png)
(Das Event ist ganztägig am 21. und 22.)

Im JSON wird das anscheinend nur dadurch abgebildet, dass keine Zeitangabe vorhanden ist (nur der Tag; da es ganztägig ist), und dass das Event am 23. endet.

```
       [
          "dtend",
          {},
          "date",
          "2015-02-23"
        ],
        [
          "dtstart",
          {},
          "date",
          "2015-02-21"
        ],
```

**Comment by tabascoeye** [comment]
Grafisch fände ich es ganz nice, wenn man den Kreis mit Datum einfach verlängert und die Daten ergänzt. Das könnte man auch unabhängig davon machen, ob Uhrzeiten da sind, sondern sobald das Ende Datum ungleich Startdatum ist.

Mockup:
![rzl_kalender_mockup](https://cloud.githubusercontent.com/assets/111893/5934375/c736ee1c-a6ce-11e4-9aac-d122e0715a9a.png)

Geht das mit Else.js? ;o)

**Comment by blabber** [comment]
Ich kann mir nicht vorstellen wie man das im aktuellen Zeitstrahllayout abbilden will. Vielleicht gibt es noch andere Events am selben Tag oder andere mehrtägige Events die sich überlappen. Ich glaube es ist besser nur den Starttermin anzuzeigen und das Endedatum unter der Überschrift mit auszuspiegeln.

**Comment by blabber** [comment]
Ich hab mich mal an einer einfachen Variante versucht Endzeitpunkte im Kalender anzuzeigen. Feel free to comment.

**Comment by blabber** [comment]
Um nicht mit jedem commit dieses Issue referenzieren zu müssen, verweise ich mal auf https://github.com/blabber/rzl-homepage/tree/multiday
