### ISSUE TITLE
Greenkeeper PRs

### ISSUE THREAD

**Issue by s1lvester** [raumzeitlabor/rzl-homepage#287]
@lutoma du hast bisher die greenkeeper prs immer gemerged. Gibts nen grund warum zur zeit nicht mehr?

**Comment by lutoma** [comment]
@s1lvester Nö, keinen näheren Grund außer, dass ich nicht mehr viel Zeit hatte. Können aber eigentlich quasi immer problemlos gemerget werden. Eigentlich hatte das damals @else eingerichtet, vielleicht gibt es noch Infos zu beachtenden Dingen.

**Comment by else** [comment]
nicht das ich wüßte

**Comment by s1lvester** [comment]
na dann. happy merging.
