### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-homepage#29]
See e.g. https://devblog.supportbee.com/2012/08/27/how-to-migrate-your-blog-from-wordpress-to-jekyll/

**Comment by else** [comment]
Wordpress uses /feed/ for the feed (no filename). I guess that means we need to setup a rewrite rule.

**Comment by okin** [comment]
Or present it in a way where humans also can find a link to the feed.

**Comment by else** [comment]
Sure, but backwards-compatibility is a must for feed subscribers.
