### ISSUE TITLE
Paypal Link zeigt noch auf Github

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-homepage#30]
um das zu fixen muss ich mal mit dem RZL paypal account einen button generieren.
Das Ding spuckt dann ein Stück HTML für ein POST form aus mit irgendwelchem hidden input kram.

Um nicht den häßlichen Button zu nutzen, können wir dann ein `<a> ` nutzen. Etwa so:
````html
<a href="#" onclick="document.getElementById('myform').submit(); return false;">PayPal</a>
````

**Comment by tabascoeye** [comment]
Der code ist:

````html
<form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input name="cmd" value="_s-xclick" type="hidden"><input name="hosted_button_id" value="PRKBBSYZ9EYT6" type="hidden">a href="#" alt="Spende an RaumzeitLabor e.V. mit PayPal" onclick="document.getElementById('myform').submit(); return false;">PayPal</a></form>
````

**Comment by else** [comment]
Danke! Gerade mal getestet, das Formular wird nicht benötigt. Ich bau den Link also direkt ein.

**Comment by tabascoeye** [comment]
:+1: :+1: :+1:
