### ISSUE TITLE
Add sitemap.xml

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-homepage#31]
Google wants us to provide a sitemap. Should be easy to generate with Jekyll, see http://davidensinger.com/2013/03/generating-a-sitemap-in-jekyll-without-a-plugin/

**Comment by else** [comment]
Hmm, taucht nicht auf der Webseite auf. :confused:

**Comment by blabber** [comment]
Keine Ahnung was da das Problem ist. In meinem Testjail hat das problemlos funktioniert.

Existiert die sitemap.xml denn auf dem Webserver?

**Comment by else** [comment]
Ja, liegt nicht im Commit.

**Comment by blabber** [comment]
Jetzt scheint es zu funktionieren.
