### ISSUE TITLE
Youtube Integration ist b0rken

### ISSUE THREAD

**Issue by blabber** [raumzeitlabor/rzl-homepage#318]
- Der Menüpunkt Video zeigt bei mir schon seit längerer Zeit nur noch an, dass keine Videos geladen werden konnten.

- Das Projekt C.H.A.O.S Video auf der Startseite wird nicht mehr korrekt eingebettet, seitdem der "erweiterte Datenschutzmodus" von Google verwendet wird.

Ich bin versucht das Video auf der Startseite komplett rauszuschmeißen und den Menüpunkt Video wenigstens so lange auszukommentieren bis sich jemand mal anschaut, warum er denn nicht mehr funktioniert. Vermisst hat ihn anscheinend noch niemand bisher...

**Comment by tabascoeye** [comment]
Mindestens mobil (Android, Chrome) geht das alles bei mir. Vll komischer ad-blocker?

**Comment by blabber** [comment]
Interessant. Im Internet Explorer tut das tatsächlich. Im Firefox nicht (weder unter Windows noch FreeBSD). Ist aber nicht auszuschliessen, dass das an meiner Konfig liegt.

**Comment by tabascoeye** [comment]
Stimmt doch und Quelle des Problems ist der "Content-Security-Policy" header, den mit mitsenden und da drin steht:

    Content-Security-Policy | default-src 'self'; script-src 'self' gdata.youtube.com content.googleapis.com
    api.tumblr.com; connect-src 'self' s.rzl.so status.raumzeitlabor.de; style-src 'self' 'unsafe-inline'; img-src
    'self' data: *.tile.openstreetmap.org i.ytimg.com *.media.tumblr.com *.edgecastcdn.net; frame-src https://www.youtube.com/embed/

und da kommt youtube-nocookie.com eben nicht vor. Deshalb wird der content von dem <iframe> nicht geladen.
Der Internet Explodierer scheißt da wohl drauf...

das wäre im rzl-homepage-docker zu fixen. ich mach mal ein issue aud

**Comment by tabascoeye** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src

**Comment by tabascoeye** [comment]
Hab im rzl-homepage-docker repo folgenden PR erstellt:
https://github.com/raumzeitlabor/rzl-homepage-docker/pull/6

**Comment by blabber** [comment]
raumzeitlabor/rzl-homepage-docker#6 ist gemerged.

Done.
