### ISSUE TITLE
Mobile Darstellung von Events verdeckt Dinge

### ISSUE THREAD

**Issue by raphaelm** [raumzeitlabor/rzl-homepage#33]
Das könnte man noch optimaler positionieren :)

https://files.rami.io/f/862458bbf6/

**Comment by else** [comment]
Ist mir auch schon aufgefallen, danke für den Hinweis. Sollte vermutlich am einfachsten mit einer Mediaquery gehen…?

**Comment by raphaelm** [comment]
Ich denke auch…
