### ISSUE TITLE
upgrade Jekyll

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-homepage#332]
Our jekyll version is fixed to 2.5.3. Current is 3.6.x

I tried to install:

* pagination is now a plugin, which needs to be added to Gemfile as separate gem to be installed
* _config.yml needs to be updated to use the plugin

BUT:
The pagination works, deep-links to the individual posts are broken (i.e. post html pages seem to get deleted but not re-created)

@else can you help?

**Comment by else** [comment]
I might have a look yeah

**Comment by silsha** [comment]
Solved by #334
