### ISSUE TITLE
Asymmetrische Schriftposition in der mobilen Navi

### ISSUE THREAD

**Issue by raphaelm** [raumzeitlabor/rzl-homepage#34]
Ich finde die neue Website total geil, sonst würde ich nicht mit so kleinkarierten Punkten anfangen, aber das sieht noch komisch aus:

https://files.rami.io/f/6f65046347/

**Comment by else** [comment]
Meinst Du das Menü oder den Paginator vom Kalender? Das mit dem Menü ist mir auch schon aufgefallen, aber da hab ich ehrlich gesagt keine Ahnung, woran das liegt. Anyone?

**Comment by raphaelm** [comment]
Die Webfont scheint an der Stelle einfach miserabel zu sein. Das können wir entweder ignorieren oder mit Padding ausgleichen, wenn es in allen Browsern so aussieht.

**Comment by else** [comment]
Ignorieren wirs.
