### ISSUE TITLE
Endless scrolling Probleme in Mobil

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-homepage#35]
Auf chrome Android macht das endless scrolling auf /Bilder komische Dinge.
Nach ein paar Sekunden lädt scheinbar alles neu.
In Wirklichkeit wird der nächste Satz Bilder geladen.
Das geht ein paar mal so bis alle Bilder geladen sind.

Ich denke die Information, ob die Seite bis zum Ende gescrollt wurde wird beim Mobil Browser falsch interpretiert

**Comment by else** [comment]
Danke für den Hinweis, da ist irgendwas schräg. Guck ich mir mal bei Gelegenheit an. Die Bilderseite hat in der Tat noch ein paar Bugs.

Ich hatte letzten den Eindruck, dass zumindest ein Problem, nämlich die Anzeige der Bilder an sich bei Mobilbrowsern von Rundungsfehlern kommt.

**Comment by blabber** [comment]
Das Problem ist zumindest nicht auf Chrome Android beschränkt. Das Problem besteht auch beim Jolla Browser (Firefoxbasiert).

**Comment by else** [comment]
related to #5
