### ISSUE TITLE
No address listed, only a route description?

### ISSUE THREAD

**Issue by KopfKrieg** [raumzeitlabor/rzl-homepage#397]
Hey there,

I just took a look at your website, and unfortunately couldn't find an address. Only a route description: https://raumzeitlabor.de/kontakt/anfahrt/

While this is great (mostly for neurotypical people though, but I'd keep it anyway, because it got a few advantages), I'd also love to have an address listed somewhere near the description (maybe directly at the start?). The embedded Open Street Map also won't load¹ for me, so … no idea where the RaumZeitLabor is (and the address is in the imprint is not always the address of the location).

[1] This is a different issue, and I can't find the error. Everything's loading fine, nothing gets blocked, the OSM should be rendered, but unfortunately, somehow, it isn't

**Comment by Ranlvor** [comment]
Hi @KopfKrieg,

to answer the question quickly: the address in our imprint is our address.

RaumZeitLabor e.V.
Weinheimer Strasse 58-60
68309 Mannheim

One hint for the correctness is that Anfahrt ends at Weinheimer Strasse, too.

I'll leave this issue open for the people maintaining the website to see and decide what to do.
