### ISSUE TITLE
Document how to add events

### ISSUE THREAD

**Issue by blabber** [raumzeitlabor/rzl-homepage#48]
Reading the proxy rules in the gruntfile, it seems we are using fruux.com to manage events. This should be documented somewhere.

Questions in this context:
* Do I need to authenticate?
* If yes, is there a raumzeitlabor account that can be used or do I need to register individually?

**Comment by else** [comment]
https://wiki.raumzeitlabor.de/wiki/Webseite#Events

**Comment by blabber** [comment]
Ooops, didn't notice that there is documentation in the Wiki. Should probably be linked to from the homepage. Sorry for the noise.

Closing this issue as documentation exists.
