### ISSUE TITLE
Layout broken due to misformatted blogpost

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-homepage#50]
Between
* RGB2R v11 - Das Retro-Gaming-Event in Heidelberg
* Sticken leicht gemacht - Workshop für Kinder
(currently on page 2)

Haven't identified the blogpost that is causing the problems.

**Comment by blabber** [comment]
Fun Fact: I can't reproduce the layout issue in my development jail, I can see it in the live version though.

**Comment by else** [comment]
That's very likely because we don't run htmlmin during `grunt serve` runs.

**Comment by blabber** [comment]
Right. Now I was able to reproduce this issue and hunt down the culprit.

**Comment by blabber** [comment]
For the record: `grunt serve:dist` serves the release build.

**Comment by else** [comment]
Thanks, maybe we should add a section on the build targets to the README.
