### ISSUE TITLE
Create exhibit of "showcase" projects

### ISSUE THREAD

**Issue by elsbrock** [raumzeitlabor/rzl-homepage#60]
I was thinking about creating dedicated pages for some cool projects, e.g. gopherspace crawler, height trimming of laser desk. Yay, nay?

**Comment by tabascoeye** [comment]
yay. If we start with some, mayber we can create more incentive to make a short documentation of projects. 
More so than the ugly mediawiki

**Comment by else** [comment]
Well the wiki definitely has its purpose, but it's more like internal documentation, right.
