### ISSUE TITLE
Make sure build works on OS X

### ISSUE THREAD

**Issue by else** [raumzeitlabor/rzl-homepage#61]
We know that our build works on Linux and FreeBSD, however our Apple friends have not managed to get it running so far. 

I would like to know if this is a technical or skill problem.

**Comment by else** [comment]
Maybe @mschuetz can help?

**Comment by tabascoeye** [comment]
we should provide a .dmg file :+1:

**Comment by mschuetz** [comment]
When I run ```grunt serve```, it fails because it can't find jekyll. Apparently because it uses the system-wide ruby installation, as opposed to the one I installed with rbenv. Is this the problem you're referring to?

**Comment by else** [comment]
Well jekyll is a build-dep, so that's fine. I think it failed for @thinkJD during `bower install`.

**Comment by mschuetz** [comment]
If I perform a system-wide installation of jekyll, ```grunt serve``` works.

**Comment by else** [comment]
Thanks! (You can install jekyll locally using `bundler`.)

**Comment by mschuetz** [comment]
I already installed it within the ruby installation I set up with rbenv, which imo should work, too.
