### ISSUE TITLE
Strange behaviour on android?

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/rzl-homepage#70]
I have a strange effect on android:
When I navigate to /events, apparently a new intent is fired and I get asked which browser I want to use (since I have both chrome and dolphin, I don't have one assigned permanently)
The only link where this happens is /events.
Any idea about that?

**Comment by else** [comment]
Can you describe the exact steps to reproduce?

**Comment by tabascoeye** [comment]
After selecting "events" from the menu in chrome, this is shown:
https://www.dropbox.com/s/hkz25fv14jpqf2k/Screenshot_2015-02-15-21-01-42.png?dl=0

**Comment by tabascoeye** [comment]
You probably need two browsers installed and no default one configured to reproduce

**Comment by else** [comment]
I can reproduce this.

**Comment by else** [comment]
I will have a look at this with Chrome remote debugging.

**Comment by tabascoeye** [comment]
Like a true web dev ninja :+1:

**Comment by else** [comment]
It seems to be related to the link target's name, "/events" and "events" both trigger the behavior.

**Comment by tabascoeye** [comment]
jupp doesn't happen in Dolphin. ==> Chrome Android Bug?

**Comment by else** [comment]
I don't think it's a bug. Anyone volunteers to ask on stackoverflow.com?

**Comment by tabascoeye** [comment]
Just stumbled over other websites doing this.
It looks like a URL with "events" in it somewhere fires a new intent. Pretty weird.
But I propose to close this as it's an android behavior, not our website

**Comment by lutoma** [comment]
I guess we could try renaming the page to /calendar or something if that fixes the behaviour?

**Comment by tabascoeye** [comment]
how many links would that break? :anguished:

**Comment by else** [comment]
Just add a redirect to the webserver config.

**Comment by lutoma** [comment]
Did you both test this when having Dolphin installed, btw? Maybe that particular browser just has /events URLs in their intents file, in which case I'd say this is more of a browser/app bug than something we should fix.

Also, instead of having to change the entire URL, maybe adding a fake GET parameter suffices?

**Comment by tabascoeye** [comment]
I did have Dolphin installed the first time I stumbled over this.
I no longer have it, but Yatse (remote app for Kodix/xmbc) was in the list of avialable apps on this strange "events" intent.

BUT. I can no longer reproduce it today on any website that has an events URL ;_;
So maybe it is fixed now or something. (ARGH!)

suggest to close this

**Comment by tabascoeye** [comment]
stale
