### ISSUE TITLE
Weiterleitung raumzeitlabor.de/wiki auf wiki.raumzeitlabor.de

### ISSUE THREAD

**Issue by felicitus** [raumzeitlabor/rzl-homepage#75]
Moin,

leider ist bei der Umstellung die Umleitung von raumzeitlabor.de/wiki/<Seitenname> auf http://wiki.raumzeitlabor.de/wiki/<Seitenname> kaputtgegangen. Einige Seiten verlinken aber noch darauf.

Vorschlag für Umleitungen:

http://raumzeitlabor.de/wiki/<Seitenname> auf https://wiki.raumzeitlabor.de/wiki/<Seitenname>
http://www.raumzeitlabor.de/wiki/<Seitenname> auf https://wiki.raumzeitlabor.de/wiki/<Seitenname>

Sofern möglich:
http://wiki.raumzeitlabor.de/<Seitenname> auf https://wiki.raumzeitlabor.de/wiki/<Seitenname>

**Comment by blabber** [comment]
@else, wer kann denn die von @felicitus angesprochenen Weiterleitungen anlegen? Ich habe keine Ahnung wie wir die Seiten letzendlich ausliefern, aber ich vermute mal, dass da irgendein httpd oder proxy umkonfiguriert werden muss, oder?

**Comment by else** [comment]
So ist es, das wäre das NOC. Allerdings dachte ich bereits drüber nach, auch die Config mit einzuchecken.

**Comment by else** [comment]
Erledige ich, wenn ich unser Wiki auf den neuen Server umziehe.

siehe raumzeitlabor/rzl-homepage-docker#1

**Comment by else** [comment]
Done:

    1 % curl -D- https://wiki.raumzeitlabor.de/                                     
    HTTP/1.1 301 Moved Permanently                                                  
    Server: nginx                                                                   
    Date: Wed, 11 Mar 2015 22:50:56 GMT                                             
    Content-Type: text/html; charset=utf-8                                          
    Transfer-Encoding: chunked                                                      
    Connection: keep-alive                                                          
    X-Powered-By: PHP/5.5.9-1ubuntu4.6                                              
    X-Content-Type-Options: nosniff                                                 
    Vary: Accept-Encoding, Cookie                                                   
    Cache-Control: s-maxage=1200, must-revalidate, max-age=0                        
    Last-Modified: Wed, 11 Mar 2015 22:50:56 GMT                                    
    Location: https://wiki.raumzeitlabor.de:443/wiki/Hauptseite                     
    Strict-Transport-Security: max-age=31536000; includeSubdomains
