### ISSUE TITLE
Implement tag based whitelist filter for tumblr pictures

### ISSUE THREAD

**Issue by blabber** [raumzeitlabor/rzl-homepage#86]
As discussed in #85 limit the pictures showcased in /bilder to a certain tag. Document this filter and give some hints which pictures should be whitelisted and which not. Whitelist an example set of pictures before merging this feature.

**Comment by blabber** [comment]
Today I learned: Never touch the gallery. No interest in endless discussion and mutual accusations.

**Comment by else** [comment]
The Tumblr API supports a `tag=…` parameter that can be used.

**Comment by tabascoeye** [comment]
stale
